- repo: https://github.com/prettier/prettier
  rev: "" # Use the sha or tag you want to point at
  hooks:
    - id: prettier

- repo: https://github.com/golangci/golangci-lint
  rev: ""
  hooks:
    - id: golangci-lint
