language: go
go:
  - 1.7
node_js: '7'
env:
  - DEP_VERSION="0.3.2"
before_install:
- nvm install 6.9
- nvm use 6.9
# Download the binary to bin folder in $GOPATH
install:
- npm install -g yarn
- go get -u github.com/golang/dep/...
- cd backend/
- dep ensure
- cd ..
before_script:
- cd frontend/
- yarn install
# - cp src/config.example.js src/config.js
- cd ..
script:
- cd backend/
- go test -v ./...
- cd ..
- cd frontend/
- npm test -- --coverage
- cd ..
after_success:
- cd backend/
- bash <(curl -s https://codecov.io/bash)
- cd ..
- cd frontend/
- bash <(curl -s https://codecov.io/bash)
- cd ..