language: go
go:
  - 1.9
node_js: "7"
services:
  - mysql
env:
  global:
    - DEP_VERSION="0.3.2"
    - DB_USERNAME=root
    - DB_PASSWORD=
    - DB_DATABASE_TEST=food_test
before_install:
  - nvm install 6.9
  - nvm use 6.9
install:
  - pip install --user awscli
  - npm install -g yarn
  - go get -u github.com/golang/dep/...
  - cd backend/
  - dep ensure
  - cd ..
before_script:
  - mysql -e 'CREATE DATABASE food_test;'
  - cd ui/
  - yarn install
  # - cp src/config.example.js src/config.js
  - cd ..
script:
  - cd backend/
  - ./test_cov.sh
  - cd ..
  - cd ui/
  - npm test -- --coverage
  - npm run build
  - cd ..
after_success:
  - cd backend/
  - bash <(curl -s https://codecov.io/bash)
  - cd ..
  - cd ui/
  - bash <(curl -s https://codecov.io/bash)
  - cd ..

deploy:
  # Deploy master to s3
  on:
    branch: master
  provider: s3
  # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: recipehub-frontend
  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  local_dir: ui/build
  cache_control: "max-age=180"
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
