# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: food
      POSTGRES_PASSWORD: food
      POSTGRES_DB: food