# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: gourd
      POSTGRES_PASSWORD: gourd
      POSTGRES_DB: food
    command: ["postgres", "-c", "log_statement=all"]
  jaeger:
    container_name: food-jaeger
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - 5778:5778
      - 16686:16686 # UI
      - 14268:14268
      - 9411:9411
    image: "jaegertracing/all-in-one:latest"
  gourd:
    build:
      context: .
    depends_on:
      - db
      - jaeger
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      BYPASS_AUTH: "true"
      JWT_KEY: "foo"
    ports:
      - "4242:4242"

  ui:
    build:
      context: ui
    stdin_open: true
    depends_on:
      - gourd
    environment:
      REACT_APP_API_URL: http://gourd:4242
      CI: "true"
    ports:
      - "3001:3001"
    volumes:
      - ./.git:/work/.git
      - ./ui/cypress:/work/cypress
      - ./ui/coverage:/work/coverage

  usda:
    build:
      context: usda
    depends_on:
      - gourd
      - db
    environment:
      DB_DSN: postgresql://gourd:gourd@db:5432/food
      CI: "true"
