# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: food
      POSTGRES_PASSWORD: food
      POSTGRES_DB: food
  jaeger:
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - 5778:5778
      - 16686:16686 # UI
      - 14268:14268
      - 9411:9411
    image: "jaegertracing/all-in-one:1.15.1"
