severity = "error"
confidence = 0.8

# want CI to fail on warnings + errors
errorCode = -1
warningCode = -1

# https://github.com/mgechev/revive#available-rules
[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.unhandled-error]
    arguments = ["fmt.Fprintf","fmt.Fprint","fmt.Printf","fmt.Println","resultRows.Close","res.Body.Close","server.Shutdown"]
[rule.constant-logical-expr]