# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build_backend:
    docker:
      # specify the version
      - image: circleci/golang:1.13
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci-demo-go
          POSTGRES_DB: circle_test
    working_directory: ~/work/
    steps:
      - checkout
      - run: make test

  build_ui:
    docker:
      - image: node:9.3.0
    working_directory: ~/work
    steps:
      - checkout
      - run: echo "todo"
      # - run: cd ui && yarn install
      # - run: cd ui && yarn test
workflows:
  version: 2
  build_fullstack:
    jobs:
      - build_ui
      - build_backend
