# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build_backend:
    docker:
      # specify the version
      - image: circleci/golang:1.11
        environment:
          - DB_USERNAME: root
          - DB_PASSWORD: root
          - DB_DATABASE_TEST: food_test
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD: root
          - MYSQL_DATABASE: food_test
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: ~/food/
    steps:
      - checkout
      - run: go build ./...
      - run: ./test.sh

  build_ui:
    docker:
      - image: node:9.3.0
    working_directory: ~/food
    steps:
      - checkout
      - run: cd ui && yarn install
      - run: cd ui && yarn test
workflows:
  version: 2
  build_fullstack:
    jobs:
      - build_ui
      - build_backend
