[package]
name = "gourd_common"
version = "0.1.0"
authors = ["Nicky Semenza <nicky@nickysemenza.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

openapi = {path = "../openapi"}
ingredient = {git = "https://github.com/nickysemenza/ingredient-parser", branch = "main"}
serde = { version = "1.0", features = ["derive"] }


[profile.dev]
split-debuginfo = "unpacked"
# https://www.reddit.com/r/rust/comments/msymvm/reducing_rust_incremental_compilation_times_on/