name: Deploy to Fly
on:
  push:
    branches: [master, dev]
jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step runs `flyctl deploy`.
      - run: curl -L https://fly.io/install.sh | sh -s 0.0.190
      - uses: superfly/flyctl-actions@master
        with:
          args: "deploy"
      - run: "/home/runner/.fly/bin/flyctl deploy --config ui/ --dockerfile ui/Dockerfile  . -v"
