name: Deploy to Fly
on:
  push:
    branches: [master]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: curl -L https://fly.io/install.sh | sh -s 0.0.190
      - uses: superfly/flyctl-actions@master
        name: deploy API
        with:
          args: "deploy"
          # https://github.com/superfly/flyctl/issues/400
      - run: "/home/runner/.fly/bin/flyctl deploy --config ui/ --dockerfile ui/Dockerfile  . -v"
        name: deploy UI
