on: [push]

name: rust build + test

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true # https://github.com/launchbadge/sqlx/tree/master/sqlx-cli#force-building-in-offline-mode

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: ["rust/common", "rust/w", "rust/s"]
    steps:
      - uses: actions/checkout@v2
      - name: cargo build ${{ matrix.crate }}
        run: cargo build --verbose
        working-directory: ${{ matrix.crate }}
      - name: cargo test
        run: cargo test --verbose
        working-directory: ${{ matrix.crate }}
