on: [push]

name: rust build + test

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true # https://github.com/launchbadge/sqlx/tree/master/sqlx-cli#force-building-in-offline-mode

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: ["common", "w", "s"]
    steps:
      - uses: actions/checkout@v2
      - name: cargo build rust/${{ matrix.crate }}
        run: cargo build --verbose
        working-directory: rust/${{ matrix.crate }}
      - name: cargo test
        run: cargo test --verbose
        working-directory: rust/${{ matrix.crate }}
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: -t 120 --manifest-path rust/${{ matrix.crate }}/Cargo.toml --output-dir rust/${{ matrix.crate }}/.cov --out Xml -- --test-threads 1
          version: "0.15.0"

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.4.0
        with:
          directory: rust/${{ matrix.crate }}/.cov
          path_to_write_report: rust/${{ matrix.crate }}/.cov/codecov_report.txt
          flags: ${{ matrix.crate }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-${{ matrix.crate }}
          path: rust/${{ matrix.crate }}/.cov
