on: [push]

name: rust build + test

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true # https://github.com/launchbadge/sqlx/tree/master/sqlx-cli#force-building-in-offline-mode

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: ["rust/common", "rust/w", "rust/s"]
    steps:
      - uses: actions/checkout@v2
      - name: cargo build ${{ matrix.crate }}
        run: cargo build --verbose
        working-directory: ${{ matrix.crate }}
      - name: cargo test
        run: cargo test --verbose
        working-directory: ${{ matrix.crate }}
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: -t 120 --root ${{ matrix.crate }} -- --test-threads 1
          version: "0.15.0"

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.2.2
        with:
          directory: ${{ matrix.crate }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{ matrix.crate }}/cobertura.xml
